
//for flag images we directly use free links found in country "flags api"
//currency code:country code
export const countryList = {
    "AFN": "AF",
    "ALL": "AL",
    "DZD": "DZ",
    "EUR": "AD",
    "AOA": "AO",
    "ARS": "AR",
    "AMD": "AM",
    "AUD": "AU",
    "AZN": "AZ",
    "BHD": "BH",
    "BDT": "BD",
    "BYN": "BY",
    "BRL": "BR",
    "BGN": "BG",
    "CAD": "CA",
    "CNY": "CN",
    "COP": "CO",
    "CZK": "CZ",
    "DKK": "DK",
    "EGP": "EG",
    "INR": "IN",
    "IDR": "ID",
    "IRR": "IR",
    "IQD": "IQ",
    "ILS": "IL",
    "JPY": "JP",
    "KZT": "KZ",
    "KWD": "KW",
    "MYR": "MY",
    "MXN": "MX",
    "MAD": "MA",
    "NZD": "NZ",
    "NGN": "NG",
    "NOK": "NO",
    "PKR": "PK",
    "PHP": "PH",
    "PLN": "PL",
    "QAR": "QA",
    "RON": "RO",
    "RUB": "RU",
    "SAR": "SA",
    "SGD": "SG",
    "ZAR": "ZA",
    "KRW": "KR",
    "SEK": "SE",
    "CHF": "CH",
    "THB": "TH",
    "TRY": "TR",
    "UAH": "UA",
    "AED": "AE",
    "GBP": "GB",
    "USD": "US",
    "VND": "VN",
    "YER": "YE",
    "ZWL": "ZW"
};

//console.log("in countrylist")
